In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
n = 500
x1 = np.random.rand(n)*100
x2 = np.random.rand(n)*100
x3 = np.random.rand(n)*100
y = -30*x1 + 40*x2 +70*x3+ 100 + np.random.randn(n)*100

In [3]:
z=200
print(x1[z],x2[z],x3[z],y[z])
print(-30*x1[z],40*x2[z],70*x3[z],y[z])
print(-30*x1[z]+40*x2[z]+70*x3[z]+100,y[z])

34.021125687525476 59.02658063024499 53.46601756220986 5234.520111925479
-1020.6337706257643 2361.0632252098 3742.6212293546905 5234.520111925479
5183.050683938726 5234.520111925479


In [4]:
print(np.random.rand(10)*100)

[62.34078422 46.26050019 76.98443345  5.64458208 72.73588445 69.23862422
 75.50447079 12.31551167 74.5164934  73.86116789]


In [5]:
print(np.random.randn(10)*100)

[ 111.94207001 -227.09132846  -57.31283328   77.97421172   71.63988508
  -89.87841829  -75.85425622 -158.95483136 -146.10974452 -232.4513916 ]


In [6]:
# Separamos nuestros datos en entrenamiento y test. X se denota con mayúscula ya que incluye dos atributos
from sklearn.model_selection import train_test_split

X = np.vstack((x1,x2,x3)).T

print(X)
print(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=88)

print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

[[94.6793816  59.76491382 25.75540173]
 [28.60938886 30.44432084 39.55433754]
 [48.88487449 64.16150022 56.3742197 ]
 ...
 [ 4.61560867 87.80970882 21.10982825]
 [13.92201006 10.6472387  68.34773876]
 [18.59392559  2.40432396 81.19244015]]
[ 1671.31913587  3217.23149053  5153.10162112  4922.12917261
  5681.66999638  2160.86156245  4835.08650005  6198.51771167
  3671.604632    3910.01624667  -276.68900908  2717.49279293
  9374.58515781  3086.01159975  5752.78893626  6742.57596539
  1303.35668052    54.34002795  6690.64395567  5836.31226057
  6597.0950015   4133.67241122  6060.87620045  6761.65223417
  3178.06718543  4606.51462673  5451.68382865  5428.29271421
  6357.94644361  5664.91909075  6521.75216381  5536.47975262
   882.87293399  4574.72015696  5989.23689357  4618.45042396
  5010.8910035   3050.16402799  6949.29801575  2804.50723588
  1926.11401177  3953.29671424  3392.22965801  5596.18929914
  7187.89569292  2445.2206204   2127.53692918  4334.59297572
  3651.75177096  1123.983985

In [7]:
# Instanciamos nuestra regresión lineal y la entrenamos
from sklearn.linear_model import LinearRegression

linear_model = LinearRegression()

linear_model.fit(X_train, y_train)

LinearRegression()

In [8]:
# Obtenemos los componentes de nuestro regresor. A diferencia del regresor con un solo atributo, aquí tenemos dos pendientes

print('Las pendientes del modelo de regresión lineal son:', linear_model.coef_)
print('La ordenada al origen del modelo de regresión lineal es:', linear_model.intercept_)

Las pendientes del modelo de regresión lineal son: [-29.99380891  39.88581894  69.85816544]
La ordenada al origen del modelo de regresión lineal es: 115.69892301974232


In [9]:
from sklearn.metrics import mean_squared_error
import seaborn as sns

y_train_pred = linear_model.predict(X_train)
y_test_pred = linear_model.predict(X_test)

rmse_train = np.sqrt(mean_squared_error(y_train, y_train_pred))
rmse_test = np.sqrt(mean_squared_error(y_test, y_test_pred))
print(f'Raíz del error cuadrático medio en Train: {rmse_train}')
print(f'Raíz del error cuadrático medio en Test: {rmse_test}')

Raíz del error cuadrático medio en Train: 95.85518831206033
Raíz del error cuadrático medio en Test: 105.2370126859141


In [10]:
df = pd.read_csv('data_regression.csv',  index_col=0)

In [11]:
df

X1         X2        X3          y
0    -10.000000   0.000000 -5.000000  10.958481
1     -9.986658   0.014676 -4.996664   8.991666
2     -9.973316   0.029353 -4.993329  10.398068
3     -9.959973   0.044029 -4.989993  11.759961
4     -9.946631   0.058706 -4.986658  10.177304
...         ...        ...       ...        ...
1495   9.946631  21.941294 -0.013342   1.208277
1496   9.959973  21.955971 -0.010007   1.814573
1497   9.973316  21.970647 -0.006671   0.791170
1498   9.986658  21.985324 -0.003336   1.207057
1499  10.000000  22.000000  0.000000   0.993813

[1500 rows x 4 columns]

In [14]:
import pandas as pd
import numpy as np
import plotly.express as px

n = 1500
X1 = np.linspace(-10,10,n)
X2 = np.linspace(0,22,n)
X3 = np.linspace(-5,0,n)

y_real = -1.5*X1 + 0.5*X2 + 2*X3 + 5

linear_generator = y_real + np.random.randn(n)

# pd.DataFrame({'X1': X1,'X2': X2,'X3': X3, 'y' :linear_generator}).to_csv('data_regression2.csv')

In [15]:
linear_generator

array([10.10306998,  9.59353388,  9.07352263, ..., -0.02316714,
        1.84404499,  2.05835498])