In [12]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error
from sklearn import metrics


In [2]:
df = pd.read_csv ('data_regression.csv', index_col=0)

In [3]:
df

X1         X2        X3          y
0    -10.000000   0.000000 -5.000000  10.958481
1     -9.986658   0.014676 -4.996664   8.991666
2     -9.973316   0.029353 -4.993329  10.398068
3     -9.959973   0.044029 -4.989993  11.759961
4     -9.946631   0.058706 -4.986658  10.177304
...         ...        ...       ...        ...
1495   9.946631  21.941294 -0.013342   1.208277
1496   9.959973  21.955971 -0.010007   1.814573
1497   9.973316  21.970647 -0.006671   0.791170
1498   9.986658  21.985324 -0.003336   1.207057
1499  10.000000  22.000000  0.000000   0.993813

[1500 rows x 4 columns]

In [70]:
X = df[['X1', 'X2', 'X3']]
y = df['y'].values.reshape(-1,1)

In [71]:
y

array([[10.9584811 ],
       [ 8.99166602],
       [10.39806802],
       ...,
       [ 0.79116965],
       [ 1.20705698],
       [ 0.99381329]])

In [72]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [73]:
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [74]:
model.coef_

array([[-0.19847621, -0.21832383, -0.04961905]])

In [75]:
model.intercept_

array([7.76307606])

In [76]:
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

print('el r2 es: ', {r2})
print('el mse es: ', {mse})

el r2 es:  {0.8674696631382685}
el mse es:  {0.9727749734476564}
